# Generated by Django 5.1.6 on 2025-04-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proiectvet', '0002_adauga_specii_rasa_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rasa',
            options={'verbose_name_plural': 'Rase'},
        ),
        migrations.AlterModelOptions(
            name='specie',
            options={'verbose_name_plural': 'Specii'},
        ),
    ]
