# Generated by Django 5.1.6 on 2025-05-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectvet', '0003_alter_rasa_options_alter_specie_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('sex', models.BooleanField(default=False)),
                ('data_nasterii', models.DateField()),
                ('id_proprietar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proiectvet.client')),
                ('id_rasa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proiectvet.rasa')),
            ],
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('anamneza', models.TextField()),
                ('temperatura', models.FloatField()),
                ('greutate', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('observatii', models.TextField()),
                ('investigatii', models.FileField(upload_to='imagistica/')),
                ('id_pacient', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='proiectvet.pacient')),
            ],
        ),
    ]
