# Generated by Django 5.1.6 on 2025-05-04 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectvet', '0004_client_pacient_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='microcip',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='pacient',
            name='sterilizat',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Deparazitare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('data_administrare', models.DateField()),
                ('id_pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectvet.pacient')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_vaccin', models.CharField(max_length=100)),
                ('data_vaccinare', models.DateField()),
                ('id_pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectvet.pacient')),
            ],
        ),
    ]
