# Generated by Django 5.1.6 on 2025-05-04 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectvet', '0005_pacient_microcip_pacient_sterilizat_deparazitare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consult',
            name='id_pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proiectvet.pacient'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='investigatii',
            field=models.FileField(blank=True, upload_to='imagistica/'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='id_proprietar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectvet.client'),
        ),
    ]
