# Generated by Django 5.1.6 on 2025-05-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectvet', '0006_alter_consult_data_alter_consult_id_pacient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
