# Generated by Django 5.1.6 on 2025-05-05 09:43

import django.db.models.deletion
import django.utils.timezone
import proiectvet.models.consult
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiectvet', '0007_alter_consult_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='investigatii',
        ),
        migrations.AddField(
            model_name='consult',
            name='analize',
            field=models.FileField(blank=True, upload_to=proiectvet.models.consult.analize_path),
        ),
        migrations.AddField(
            model_name='consult',
            name='imagistica',
            field=models.FileField(blank=True, upload_to=proiectvet.models.consult.imagistica_path),
        ),
        migrations.AddField(
            model_name='consult',
            name='tratament',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consult',
            name='id_pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proiectvet.pacient'),
        ),
    ]
