# Generated by Django 5.1.6 on 2025-12-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proiectvet', '0008_remove_consult_investigatii_consult_analize_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deparazitare',
            options={'verbose_name_plural': 'Deparazitari'},
        ),
        migrations.AlterModelOptions(
            name='vaccin',
            options={'verbose_name_plural': 'Vaccinuri'},
        ),
    ]
