from .client import ClientSerializer
from .consult import ConsultSerializer
from .deparazitare import DeparazitareSerializer
from .pacient import PacientSerializer
from .pret import PretSerializer
from .protocol import ProtocolSerializer
from .rasa import RasaSerializer
from .specie import SpecieSerializer
from .vaccin import VaccinSerializer
