# Generated by Django 5.1.6 on 2025-02-13 21:39

from django.db import migrations

def adauga_specii_default(apps, schema_editor):
    """Adauga specii predefinite in tabel."""
    Specie = apps.get_model('cabinet', 'Specie')
    specii_predefinite = ["Caine", "Pisica"]

    for specie in specii_predefinite:
        Specie.objects.get_or_create(nume=specie,
                                     defaults={"protected": True},)

def adauga_rase_default(apps, schema_editor):
    """Adauga rase predefinite, specifice fiecarei specii in tabel."""
    Rasa = apps.get_model('cabinet', 'Rasa')
    Specie = apps.get_model('cabinet', 'Specie')

    try:
        caine = Specie.objects.get(nume="Caine")
        pisica = Specie.objects.get(nume="Pisica")
    except Specie.DoesNotExist:
        return
    
    Rasa.objects.bulk_create([
        Rasa(nume="Ciobanesc German", id_specie=caine, protected=True),
        Rasa(nume="Labrador", id_specie=caine, protected=True),
        Rasa(nume="Sphynx", id_specie=pisica, protected=True),
        Rasa(nume="Europeana", id_specie=pisica, protected=True),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(adauga_specii_default),
        migrations.RunPython(adauga_rase_default),
    ]
