# Generated by Django 5.1.6 on 2025-02-13 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, unique=True)),
                ('protected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, unique=True)),
                ('protected', models.BooleanField(default=False)),
                ('id_specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.specie')),
            ],
        ),
    ]
