# Generated by Django 5.1.6 on 2025-02-16 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_adauga_specii_rasa_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('data_nastere', models.DateField()),
                ('id_proprietar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.client')),
                ('id_rasa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabinet.rasa')),
            ],
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('anamneza', models.TextField()),
                ('temperatura', models.FloatField()),
                ('greutate', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('observatii', models.TextField()),
                ('id_pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.pacient')),
            ],
        ),
    ]
