from .client import ClientViewSet
from .consult import ConsultViewSet
from .deparazitare import DeparazitareViewSet
from .pacient import PacientViewSet
from .pret import PretViewSet
from .protocol import ProtocolViewSet
from .rasa import RasaViewSet
from .specie import SpecieViewSet
from .vaccin import VaccinViewSet
